# Generated by Django 4.0.1 on 2023-08-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0019_rendezvous_dte_sortie_ancien_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='dte_sortie_ancien_loc',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='edl',
            field=models.CharField(default='0', max_length=10, verbose_name='edl'),
        ),
    ]
